import { Metadata } from "next";
import Footer from "./Footer";
import Header from "./Header";
import "./output.css";
import { MouseOverlay } from "@/components/overlays";
import Providers from "./Providers";
import Modal from "@/components/login/modal/Modal";
import { Analytics } from "@vercel/analytics/react";
export const metadata: Metadata = {
  title: "Etan Heyman`n Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="scrollbar-none bg-black">
        <Providers>
          {/* <MouseOverlay> */}
          <Header />
          <main>{children}</main>
          <Modal />
          <Footer />
          {/* </MouseOverlay> */}
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}
