import { Metadata } from "next";
import Footer from "./Footer";
import Header from "./Header";
import "./output.css";
import Providers from "../components/providers";
import Modal from "@/components/modal/Modal";
import { Analytics } from "@vercel/analytics/react";
export const metadata: Metadata = {
  title: "Etan Heyman`n Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="scrollbar-none h-full max-h-screen overflow-hidden bg-black">
        <Providers>
          {/* <MouseOverlay> */}
          <Header />
          <main>
            {children}
          </main>
          <Modal />
          <Footer />
          {/* </MouseOverlay> */}
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}
